### PR TITLE
Postgres variation with usage of Flyway migrations

### PR DESCRIPTION
**Pull request by morki**
See https://github.com/micronaut-graal-tests/micronaut-jooq-graal/issues/2

@ilopmar I don't know how we are making databases available in tests, so I created `docker-compose.yml` file for local testing and demonstration, feel free to remove it and make other necessary steps to use it in Gitlab tests.

### CODE REVIEW

**Comment by ilopmar** [comment]
For local testing what I do is include in the README file the command to start the database using Docker. For example, take a look at Flyway Postgresql example: https://github.com/micronaut-graal-tests/micronaut-flyway-graal/blob/master_postgres/README.md

For CI I use the built-in support in Gitlab to start other docker containers: https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/blob/master/.gitlab-ci.yml#L1380-1393. In any case, don't worry too much about CI, once we have a working app here I'll modify the CI.

I have one question regarding the PR. Is there a way to configure the database (url, username and password) only in one place. I'm not criticizing your work here, so please don't get me wrong. It's just it feels strange and a little bit ugly need to configure it in 3 different places.

**Comment by morki** [comment]
@ilopmar thanks for feedback, please criticize my work, it's the best type of feedback :)

I tried something, is it better? Or can you guide me to do it better, is some idea already in your head?

**Comment by ilopmar** [comment]
Yes, that looks better :smile: 

I've pushed a new branch `master_postgres` so you may want to re-target this PR to the new branch. I think we can cleanup it a little bit and merge it using the flag `--report-unsupported-elements-at-runtime` so I can add everything to CI and then continue trying to make it work without the flag.
What do you think?

**Comment by morki** [comment]
@ilopmar Sure :)

**Comment by ilopmar** [comment]
Manually applied the changes and merged everything in `master_postgres` branch.

**Pull request closed without merging**
